# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rNormalGLM_cpp_export <- function(n, y, x, mu, P, offset, wt, dispersion, f2, f3, start, family = "binomial", link = "logit", Gridtype = 2L, n_envopt = -1L, use_parallel = TRUE, use_opencl = FALSE, verbose = FALSE) {
    .Call(`_glmbayes_rNormalGLM_cpp_export`, n, y, x, mu, P, offset, wt, dispersion, f2, f3, start, family, link, Gridtype, n_envopt, use_parallel, use_opencl, verbose)
}

rNormalGLMBlocks_cpp_export <- function(n, y, x, offset, wt, dispersion, mu, P_blocks, prior_by_block, row_blocks, f2, f3, family = "binomial", link = "logit", Gridtype = 2L, n_envopt = -1L, use_parallel = TRUE, use_opencl = FALSE, verbose = FALSE) {
    .Call(`_glmbayes_rNormalGLMBlocks_cpp_export`, n, y, x, offset, wt, dispersion, mu, P_blocks, prior_by_block, row_blocks, f2, f3, family, link, Gridtype, n_envopt, use_parallel, use_opencl, verbose)
}

rNormalReg_cpp_export <- function(n, y, x, mu, P, offset, wt, dispersion, f2, f3, start, family = "gaussian", link = "identity", Gridtype = 2L) {
    .Call(`_glmbayes_rNormalReg_cpp_export`, n, y, x, mu, P, offset, wt, dispersion, f2, f3, start, family, link, Gridtype)
}

rIndepNormalGammaReg_cpp_export <- function(n, y, x, mu, P, offset, wt, shape, rate, max_disp_perc, disp_lower, disp_upper, Gridtype, n_envopt, use_parallel, use_opencl, verbose, progbar) {
    .Call(`_glmbayes_rIndepNormalGammaReg_cpp_export`, n, y, x, mu, P, offset, wt, shape, rate, max_disp_perc, disp_lower, disp_upper, Gridtype, n_envopt, use_parallel, use_opencl, verbose, progbar)
}

rNormalGammaReg_cpp_export <- function(n, y, x, mu, P, offset, wt, shape, rate, max_disp_perc, disp_lower, disp_upper, verbose = FALSE) {
    .Call(`_glmbayes_rNormalGammaReg_cpp_export`, n, y, x, mu, P, offset, wt, shape, rate, max_disp_perc, disp_lower, disp_upper, verbose)
}

rGammaGaussian_cpp_export <- function(n, y, x, beta, wt, alpha, shape, rate, disp_lower = NULL, disp_upper = NULL, verbose = FALSE) {
    .Call(`_glmbayes_rGammaGaussian_cpp_export`, n, y, x, beta, wt, alpha, shape, rate, disp_lower, disp_upper, verbose)
}

rGammaGamma_cpp_export <- function(n, y, x, beta, wt, alpha, shape, rate, max_disp_perc, disp_lower = NULL, disp_upper = NULL, verbose = FALSE) {
    .Call(`_glmbayes_rGammaGamma_cpp_export`, n, y, x, beta, wt, alpha, shape, rate, max_disp_perc, disp_lower, disp_upper, verbose)
}

rNormalGLM_std_cpp_export <- function(n, y, x, mu, P, alpha, wt, f2, Envelope, family, link, progbar = 1L, verbose = FALSE) {
    .Call(`_glmbayes_rNormalGLM_std_cpp_export`, n, y, x, mu, P, alpha, wt, f2, Envelope, family, link, progbar, verbose)
}

EnvelopeSize_cpp_export <- function(a, G1, Gridtype, n, n_envopt, use_opencl, verbose) {
    .Call(`_glmbayes_EnvelopeSize_cpp_export`, a, G1, Gridtype, n, n_envopt, use_opencl, verbose)
}

EnvelopeBuild_cpp_export <- function(bStar, A, y, x, mu, P, alpha, wt, family, link, Gridtype, n, n_envopt, sortgrid, use_opencl, verbose) {
    .Call(`_glmbayes_EnvelopeBuild_cpp_export`, bStar, A, y, x, mu, P, alpha, wt, family, link, Gridtype, n, n_envopt, sortgrid, use_opencl, verbose)
}

EnvelopeBuild_Ind_Normal_Gamma_cpp_export <- function(bStar, A, y, x, mu, P, alpha, wt, family = "binomial", link = "logit", Gridtype = 2L, n = 1L, n_envopt = -1L, sortgrid = FALSE, use_opencl = FALSE, verbose = FALSE) {
    .Call(`_glmbayes_EnvelopeBuild_Ind_Normal_Gamma_cpp_export`, bStar, A, y, x, mu, P, alpha, wt, family, link, Gridtype, n, n_envopt, sortgrid, use_opencl, verbose)
}

EnvelopeEval_cpp_export <- function(G4, y, x, mu, P, alpha, wt, family, link, use_opencl = FALSE, verbose = FALSE) {
    .Call(`_glmbayes_EnvelopeEval_cpp_export`, G4, y, x, mu, P, alpha, wt, family, link, use_opencl, verbose)
}

EnvelopeDispersionBuild_cpp_export <- function(Env, Shape, Rate, P, y, x, alpha, n_obs, RSS_post, RSS_ML, mu, wt, max_disp_perc = 0.99, disp_lower = NULL, disp_upper = NULL, verbose = FALSE, use_parallel = TRUE) {
    .Call(`_glmbayes_EnvelopeDispersionBuild_cpp_export`, Env, Shape, Rate, P, y, x, alpha, n_obs, RSS_post, RSS_ML, mu, wt, max_disp_perc, disp_lower, disp_upper, verbose, use_parallel)
}

EnvelopeOrchestrator_cpp_export <- function(bstar2, A, y, x2, mu2, P2, alpha, wt, n, Gridtype, n_envopt, shape, rate, RSS_Post2, RSS_ML, max_disp_perc, disp_lower, disp_upper, use_parallel, use_opencl, verbose) {
    .Call(`_glmbayes_EnvelopeOrchestrator_cpp_export`, bstar2, A, y, x2, mu2, P2, alpha, wt, n, Gridtype, n_envopt, shape, rate, RSS_Post2, RSS_ML, max_disp_perc, disp_lower, disp_upper, use_parallel, use_opencl, verbose)
}

EnvelopeCentering_cpp_export <- function(y, x, mu, P, offset, wt, shape, rate, Gridtype = 2L, verbose = FALSE) {
    .Call(`_glmbayes_EnvelopeCentering_cpp_export`, y, x, mu, P, offset, wt, shape, rate, Gridtype, verbose)
}

EnvelopeSet_Grid_cpp_export <- function(GIndex, cbars, Lint) {
    .Call(`_glmbayes_EnvelopeSet_Grid_cpp_export`, GIndex, cbars, Lint)
}

EnvelopeSet_LogP_cpp_export <- function(logP, NegLL, cbars, G3) {
    .Call(`_glmbayes_EnvelopeSet_LogP_cpp_export`, logP, NegLL, cbars, G3)
}

rIndepNormalGammaReg_std_cpp_export <- function(n, y, x, mu, P, alpha, wt, f2, Envelope, gamma_list, UB_list, family, link, progbar = TRUE, verbose = FALSE) {
    .Call(`_glmbayes_rIndepNormalGammaReg_std_cpp_export`, n, y, x, mu, P, alpha, wt, f2, Envelope, gamma_list, UB_list, family, link, progbar, verbose)
}

rIndepNormalGammaReg_std_parallel_cpp_export <- function(n, y, x, mu, P, alpha, wt, f2, Envelope, gamma_list, UB_list, family, link, progbar = TRUE, verbose = FALSE) {
    .Call(`_glmbayes_rIndepNormalGammaReg_std_parallel_cpp_export`, n, y, x, mu, P, alpha, wt, f2, Envelope, gamma_list, UB_list, family, link, progbar, verbose)
}

glmb_Standardize_Model_cpp_export <- function(y, x, P, bstar, A1) {
    .Call(`_glmbayes_glmb_Standardize_Model_cpp_export`, y, x, P, bstar, A1)
}

has_opencl_cpp_export <- function() {
    .Call(`_glmbayes_has_opencl_cpp_export`)
}

get_opencl_core_count_cpp_export <- function() {
    .Call(`_glmbayes_get_opencl_core_count_cpp_export`)
}

gpu_names_cpp_export <- function() {
    .Call(`_glmbayes_gpu_names_cpp_export`)
}

