/**
 * @file opencl.h
 * @brief GLM‑specific OpenCL execution layer for glmbayes, providing GPU
 *        runners and high‑level Rcpp wrappers for f2/f3 log‑posterior and
 *        gradient evaluation.
 *
 * @namespace glmbayes::opencl
 * @brief Interfaces that connect glmbayes’ statistical kernels to their
 *        OpenCL‑ported implementations. This layer is distinct from
 *        openclPort (a general‑purpose OpenCL utility library intended
 *        for standalone use).
 *
 * @section Context
 *   The functions declared here are GLM‑specific and rely on OpenCL kernels
 *   that implement:
 *     - f2 (negative log‑posterior + prior component)
 *     - f3 (gradient of f2 with respect to β)
 *   for models whose parameter space has \(3^\ell\) faces. These kernels are
 *   typically generated by porting C++ routines (including portions of the
 *   nmath library and glmbayes’ own f2/f3 code) to OpenCL C.
 *
 *   Unlike openclPort—which provides general utilities for kernel loading,
 *   device enumeration, and Rcpp → std::vector conversion—this namespace
 *   provides the GLM‑aware execution path used internally by glmbayes,
 *   including assembly of the full OpenCL program for likelihood‑subgradient
 *   (standard‑form f2/f3) evaluation on device.
 *
 * @section ImplementedIn
 *   These declarations are implemented in:
 *     - kernel_runners.cpp (f2_f3_kernel_runner)
 *     - kernel_wrappers.cpp (f2_f3_opencl)
 *     - kernel_loader.cpp (load_likelihood_subgradient_program, USE_OPENCL)
 *
 * @section UsedBy
 *   These functions are consumed by:
 *     - EnvelopeBuild and EnvelopeDispersionBuild when GPU evaluation is enabled
 *     - rNormalGLM, rIndepNormalGammaReg, and related simulation routines
 *     - R wrappers that expose GPU‑accelerated f2/f3 evaluation to users
 *
 * @section Responsibilities
 *   Provides:
 *     - a low‑level GPU runner (f2_f3_kernel_runner) that executes the
 *       OpenCL kernel for f2/f3 evaluation on flattened buffers,
 *     - a high‑level Rcpp wrapper (f2_f3_opencl) that:
 *         • loads kernel sources via load_likelihood_subgradient_program,
 *         • flattens R matrices/vectors,
 *         • dispatches family/link‑specific kernels,
 *         • reconstructs outputs for R.
 *
 *   This module:
 *     - assumes validated inputs from R wrappers,
 *     - isolates GLM‑specific OpenCL logic from general OpenCL utilities,
 *     - enables optional GPU acceleration without altering CPU behavior.
 */


#ifndef GLMBAYES_OPENCL_H
#define GLMBAYES_OPENCL_H

#include <string>
#include <vector>
#include <Rcpp.h>

namespace glmbayes {
namespace opencl {

// -----------------------------------------------------------------------------
// Low-level OpenCL runner
// -----------------------------------------------------------------------------
//
// Executes the f2/f3 GLM kernel on the GPU.
// This is GLM-specific and belongs in glmbayes::opencl, not openclPort.
//
// kernel_source : full OpenCL program text (helpers + kernel)
// kernel_name   : e.g. "f2_f3_binomial_logit"
// l1, l2, m1    : dims (observations, coefficients, grid size)
// X_flat        : length = l1 * l2, column-major design matrix
// B_flat        : length = m1 * l2, row-major grid of β
// mu_flat       : length = l2, prior means
// P_flat        : length = l2 * l2, prior precision (row-major)
// alpha_flat    : length = l1, offsets
// y_flat        : length = l1, observed responses
// wt_flat       : length = l1, observation weights
// qf_flat       : OUT, length = m1, prior quadratic forms
// grad_flat     : OUT, length = m1 * l2, gradient w.r.t β
// progbar       : 0 = no progress, >0 = show progress bar
//
void f2_f3_kernel_runner(
    const std::string&            kernel_source,
    const char*                   kernel_name,
    int                           l1,
    int                           l2,
    int                           m1,
    const std::vector<double>&    X_flat,
    const std::vector<double>&    B_flat,
    const std::vector<double>&    mu_flat,
    const std::vector<double>&    P_flat,
    const std::vector<double>&    alpha_flat,
    const std::vector<double>&    y_flat,
    const std::vector<double>&    wt_flat,
    std::vector<double>&          qf_flat,
    std::vector<double>&          grad_flat,
    int                           progbar = 0
);


// -----------------------------------------------------------------------------
// High-level Rcpp wrapper
// -----------------------------------------------------------------------------
//
// Loads kernel sources, flattens R matrices, dispatches family/link,
// calls the runner, and reconstructs outputs for R.
//
// b      : l2 × m1 grid of β values
// y      : length l1 responses
// x      : l1 × l2 design matrix
// mu     : l2 × 1 prior mean
// P      : l2 × l2 prior precision
// alpha  : length l1 offsets
// wt     : length l1 weights
// progbar: 0 = no text bar, 1 = show progress
//
Rcpp::List f2_f3_opencl(
    std::string family,
    std::string link,
    Rcpp::NumericMatrix  b,
    Rcpp::NumericVector  y,
    Rcpp::NumericMatrix  x,
    Rcpp::NumericMatrix  mu,
    Rcpp::NumericMatrix  P,
    Rcpp::NumericVector  alpha,
    Rcpp::NumericVector  wt,
    int                  progbar = 0
);

#ifdef USE_OPENCL
// Concatenated OpenCL C source: prelude and shims from nmathopencl, selective
// nmath subset from nmathopencl, entry kernels from app_package. See inst/cl/README.md.
std::string load_likelihood_subgradient_program(
    const std::string& family,
    const std::string& link,
    const std::string& app_package = "glmbayes",
    const std::string& nmath_package = "nmathopencl");
#endif

} // namespace opencl
} // namespace glmbayes

#endif