// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rNormalGLM_cpp_export
Rcpp::List rNormalGLM_cpp_export(int n, const Rcpp::NumericVector& y, const Rcpp::NumericMatrix& x, const Rcpp::NumericVector& mu, const Rcpp::NumericMatrix& P, const Rcpp::NumericVector& offset, const Rcpp::NumericVector& wt, double dispersion, const Rcpp::Function& f2, const Rcpp::Function& f3, const Rcpp::NumericVector& start, const std::string& family, const std::string& link, int Gridtype, int n_envopt, bool use_parallel, bool use_opencl, bool verbose);
RcppExport SEXP _glmbayes_rNormalGLM_cpp_export(SEXP nSEXP, SEXP ySEXP, SEXP xSEXP, SEXP muSEXP, SEXP PSEXP, SEXP offsetSEXP, SEXP wtSEXP, SEXP dispersionSEXP, SEXP f2SEXP, SEXP f3SEXP, SEXP startSEXP, SEXP familySEXP, SEXP linkSEXP, SEXP GridtypeSEXP, SEXP n_envoptSEXP, SEXP use_parallelSEXP, SEXP use_openclSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type P(PSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type wt(wtSEXP);
    Rcpp::traits::input_parameter< double >::type dispersion(dispersionSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Function& >::type f2(f2SEXP);
    Rcpp::traits::input_parameter< const Rcpp::Function& >::type f3(f3SEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type start(startSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type family(familySEXP);
    Rcpp::traits::input_parameter< const std::string& >::type link(linkSEXP);
    Rcpp::traits::input_parameter< int >::type Gridtype(GridtypeSEXP);
    Rcpp::traits::input_parameter< int >::type n_envopt(n_envoptSEXP);
    Rcpp::traits::input_parameter< bool >::type use_parallel(use_parallelSEXP);
    Rcpp::traits::input_parameter< bool >::type use_opencl(use_openclSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(rNormalGLM_cpp_export(n, y, x, mu, P, offset, wt, dispersion, f2, f3, start, family, link, Gridtype, n_envopt, use_parallel, use_opencl, verbose));
    return rcpp_result_gen;
END_RCPP
}
// rNormalGLMBlocks_cpp_export
Rcpp::List rNormalGLMBlocks_cpp_export(int n, const Rcpp::NumericVector& y, const Rcpp::NumericMatrix& x, const Rcpp::NumericVector& offset, const Rcpp::NumericVector& wt, const Rcpp::NumericVector& dispersion, const Rcpp::NumericMatrix& mu, const Rcpp::List& P_blocks, bool prior_by_block, const Rcpp::List& row_blocks, const Rcpp::Function& f2, const Rcpp::Function& f3, const std::string& family, const std::string& link, int Gridtype, int n_envopt, bool use_parallel, bool use_opencl, bool verbose);
RcppExport SEXP _glmbayes_rNormalGLMBlocks_cpp_export(SEXP nSEXP, SEXP ySEXP, SEXP xSEXP, SEXP offsetSEXP, SEXP wtSEXP, SEXP dispersionSEXP, SEXP muSEXP, SEXP P_blocksSEXP, SEXP prior_by_blockSEXP, SEXP row_blocksSEXP, SEXP f2SEXP, SEXP f3SEXP, SEXP familySEXP, SEXP linkSEXP, SEXP GridtypeSEXP, SEXP n_envoptSEXP, SEXP use_parallelSEXP, SEXP use_openclSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type wt(wtSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type dispersion(dispersionSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type P_blocks(P_blocksSEXP);
    Rcpp::traits::input_parameter< bool >::type prior_by_block(prior_by_blockSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type row_blocks(row_blocksSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Function& >::type f2(f2SEXP);
    Rcpp::traits::input_parameter< const Rcpp::Function& >::type f3(f3SEXP);
    Rcpp::traits::input_parameter< const std::string& >::type family(familySEXP);
    Rcpp::traits::input_parameter< const std::string& >::type link(linkSEXP);
    Rcpp::traits::input_parameter< int >::type Gridtype(GridtypeSEXP);
    Rcpp::traits::input_parameter< int >::type n_envopt(n_envoptSEXP);
    Rcpp::traits::input_parameter< bool >::type use_parallel(use_parallelSEXP);
    Rcpp::traits::input_parameter< bool >::type use_opencl(use_openclSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(rNormalGLMBlocks_cpp_export(n, y, x, offset, wt, dispersion, mu, P_blocks, prior_by_block, row_blocks, f2, f3, family, link, Gridtype, n_envopt, use_parallel, use_opencl, verbose));
    return rcpp_result_gen;
END_RCPP
}
// rNormalReg_cpp_export
Rcpp::List rNormalReg_cpp_export(int n, const Rcpp::NumericVector& y, const Rcpp::NumericMatrix& x, const Rcpp::NumericVector& mu, const Rcpp::NumericMatrix& P, const Rcpp::NumericVector& offset, const Rcpp::NumericVector& wt, double dispersion, const Rcpp::Function& f2, const Rcpp::Function& f3, const Rcpp::NumericVector& start, const std::string& family, const std::string& link, int Gridtype);
RcppExport SEXP _glmbayes_rNormalReg_cpp_export(SEXP nSEXP, SEXP ySEXP, SEXP xSEXP, SEXP muSEXP, SEXP PSEXP, SEXP offsetSEXP, SEXP wtSEXP, SEXP dispersionSEXP, SEXP f2SEXP, SEXP f3SEXP, SEXP startSEXP, SEXP familySEXP, SEXP linkSEXP, SEXP GridtypeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type P(PSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type wt(wtSEXP);
    Rcpp::traits::input_parameter< double >::type dispersion(dispersionSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Function& >::type f2(f2SEXP);
    Rcpp::traits::input_parameter< const Rcpp::Function& >::type f3(f3SEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type start(startSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type family(familySEXP);
    Rcpp::traits::input_parameter< const std::string& >::type link(linkSEXP);
    Rcpp::traits::input_parameter< int >::type Gridtype(GridtypeSEXP);
    rcpp_result_gen = Rcpp::wrap(rNormalReg_cpp_export(n, y, x, mu, P, offset, wt, dispersion, f2, f3, start, family, link, Gridtype));
    return rcpp_result_gen;
END_RCPP
}
// rIndepNormalGammaReg_cpp_export
Rcpp::List rIndepNormalGammaReg_cpp_export(int n, const Rcpp::NumericVector& y, const Rcpp::NumericMatrix& x, const Rcpp::NumericVector& mu, const Rcpp::NumericMatrix& P, const Rcpp::NumericVector& offset, const Rcpp::NumericVector& wt, double shape, double rate, double max_disp_perc, Rcpp::Nullable<Rcpp::NumericVector> disp_lower, Rcpp::Nullable<Rcpp::NumericVector> disp_upper, int Gridtype, int n_envopt, bool use_parallel, bool use_opencl, bool verbose, bool progbar);
RcppExport SEXP _glmbayes_rIndepNormalGammaReg_cpp_export(SEXP nSEXP, SEXP ySEXP, SEXP xSEXP, SEXP muSEXP, SEXP PSEXP, SEXP offsetSEXP, SEXP wtSEXP, SEXP shapeSEXP, SEXP rateSEXP, SEXP max_disp_percSEXP, SEXP disp_lowerSEXP, SEXP disp_upperSEXP, SEXP GridtypeSEXP, SEXP n_envoptSEXP, SEXP use_parallelSEXP, SEXP use_openclSEXP, SEXP verboseSEXP, SEXP progbarSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type P(PSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type wt(wtSEXP);
    Rcpp::traits::input_parameter< double >::type shape(shapeSEXP);
    Rcpp::traits::input_parameter< double >::type rate(rateSEXP);
    Rcpp::traits::input_parameter< double >::type max_disp_perc(max_disp_percSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type disp_lower(disp_lowerSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type disp_upper(disp_upperSEXP);
    Rcpp::traits::input_parameter< int >::type Gridtype(GridtypeSEXP);
    Rcpp::traits::input_parameter< int >::type n_envopt(n_envoptSEXP);
    Rcpp::traits::input_parameter< bool >::type use_parallel(use_parallelSEXP);
    Rcpp::traits::input_parameter< bool >::type use_opencl(use_openclSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< bool >::type progbar(progbarSEXP);
    rcpp_result_gen = Rcpp::wrap(rIndepNormalGammaReg_cpp_export(n, y, x, mu, P, offset, wt, shape, rate, max_disp_perc, disp_lower, disp_upper, Gridtype, n_envopt, use_parallel, use_opencl, verbose, progbar));
    return rcpp_result_gen;
END_RCPP
}
// rNormalGammaReg_cpp_export
Rcpp::List rNormalGammaReg_cpp_export(int n, const Rcpp::NumericVector& y, const Rcpp::NumericMatrix& x, const Rcpp::NumericVector& mu, const Rcpp::NumericMatrix& P, const Rcpp::NumericVector& offset, const Rcpp::NumericVector& wt, double shape, double rate, Rcpp::Nullable<double> max_disp_perc, Rcpp::Nullable<double> disp_lower, Rcpp::Nullable<double> disp_upper, bool verbose);
RcppExport SEXP _glmbayes_rNormalGammaReg_cpp_export(SEXP nSEXP, SEXP ySEXP, SEXP xSEXP, SEXP muSEXP, SEXP PSEXP, SEXP offsetSEXP, SEXP wtSEXP, SEXP shapeSEXP, SEXP rateSEXP, SEXP max_disp_percSEXP, SEXP disp_lowerSEXP, SEXP disp_upperSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type P(PSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type wt(wtSEXP);
    Rcpp::traits::input_parameter< double >::type shape(shapeSEXP);
    Rcpp::traits::input_parameter< double >::type rate(rateSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type max_disp_perc(max_disp_percSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type disp_lower(disp_lowerSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type disp_upper(disp_upperSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(rNormalGammaReg_cpp_export(n, y, x, mu, P, offset, wt, shape, rate, max_disp_perc, disp_lower, disp_upper, verbose));
    return rcpp_result_gen;
END_RCPP
}
// rGammaGaussian_cpp_export
Rcpp::List rGammaGaussian_cpp_export(int n, const Rcpp::NumericVector& y, const Rcpp::NumericMatrix& x, const Rcpp::NumericVector& beta, const Rcpp::NumericVector& wt, const Rcpp::NumericVector& alpha, double shape, double rate, Rcpp::Nullable<double> disp_lower, Rcpp::Nullable<double> disp_upper, bool verbose);
RcppExport SEXP _glmbayes_rGammaGaussian_cpp_export(SEXP nSEXP, SEXP ySEXP, SEXP xSEXP, SEXP betaSEXP, SEXP wtSEXP, SEXP alphaSEXP, SEXP shapeSEXP, SEXP rateSEXP, SEXP disp_lowerSEXP, SEXP disp_upperSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type wt(wtSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type shape(shapeSEXP);
    Rcpp::traits::input_parameter< double >::type rate(rateSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type disp_lower(disp_lowerSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type disp_upper(disp_upperSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(rGammaGaussian_cpp_export(n, y, x, beta, wt, alpha, shape, rate, disp_lower, disp_upper, verbose));
    return rcpp_result_gen;
END_RCPP
}
// rGammaGamma_cpp_export
Rcpp::List rGammaGamma_cpp_export(int n, const Rcpp::NumericVector& y, const Rcpp::NumericMatrix& x, const Rcpp::NumericVector& beta, const Rcpp::NumericVector& wt, const Rcpp::NumericVector& alpha, double shape, double rate, double max_disp_perc, Rcpp::Nullable<double> disp_lower, Rcpp::Nullable<double> disp_upper, bool verbose);
RcppExport SEXP _glmbayes_rGammaGamma_cpp_export(SEXP nSEXP, SEXP ySEXP, SEXP xSEXP, SEXP betaSEXP, SEXP wtSEXP, SEXP alphaSEXP, SEXP shapeSEXP, SEXP rateSEXP, SEXP max_disp_percSEXP, SEXP disp_lowerSEXP, SEXP disp_upperSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type wt(wtSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type shape(shapeSEXP);
    Rcpp::traits::input_parameter< double >::type rate(rateSEXP);
    Rcpp::traits::input_parameter< double >::type max_disp_perc(max_disp_percSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type disp_lower(disp_lowerSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type disp_upper(disp_upperSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(rGammaGamma_cpp_export(n, y, x, beta, wt, alpha, shape, rate, max_disp_perc, disp_lower, disp_upper, verbose));
    return rcpp_result_gen;
END_RCPP
}
// rNormalGLM_std_cpp_export
Rcpp::List rNormalGLM_std_cpp_export(int n, const Rcpp::NumericVector& y, const Rcpp::NumericMatrix& x, const Rcpp::NumericMatrix& mu, const Rcpp::NumericMatrix& P, const Rcpp::NumericVector& alpha, const Rcpp::NumericVector& wt, const Rcpp::Function& f2, const Rcpp::List& Envelope, const Rcpp::CharacterVector& family, const Rcpp::CharacterVector& link, int progbar, bool verbose);
RcppExport SEXP _glmbayes_rNormalGLM_std_cpp_export(SEXP nSEXP, SEXP ySEXP, SEXP xSEXP, SEXP muSEXP, SEXP PSEXP, SEXP alphaSEXP, SEXP wtSEXP, SEXP f2SEXP, SEXP EnvelopeSEXP, SEXP familySEXP, SEXP linkSEXP, SEXP progbarSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type P(PSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type wt(wtSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Function& >::type f2(f2SEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type Envelope(EnvelopeSEXP);
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector& >::type family(familySEXP);
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector& >::type link(linkSEXP);
    Rcpp::traits::input_parameter< int >::type progbar(progbarSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(rNormalGLM_std_cpp_export(n, y, x, mu, P, alpha, wt, f2, Envelope, family, link, progbar, verbose));
    return rcpp_result_gen;
END_RCPP
}
// EnvelopeSize_cpp_export
Rcpp::List EnvelopeSize_cpp_export(const arma::vec& a, const Rcpp::NumericMatrix& G1, int Gridtype, int n, int n_envopt, bool use_opencl, bool verbose);
RcppExport SEXP _glmbayes_EnvelopeSize_cpp_export(SEXP aSEXP, SEXP G1SEXP, SEXP GridtypeSEXP, SEXP nSEXP, SEXP n_envoptSEXP, SEXP use_openclSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type G1(G1SEXP);
    Rcpp::traits::input_parameter< int >::type Gridtype(GridtypeSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type n_envopt(n_envoptSEXP);
    Rcpp::traits::input_parameter< bool >::type use_opencl(use_openclSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(EnvelopeSize_cpp_export(a, G1, Gridtype, n, n_envopt, use_opencl, verbose));
    return rcpp_result_gen;
END_RCPP
}
// EnvelopeBuild_cpp_export
Rcpp::List EnvelopeBuild_cpp_export(Rcpp::NumericVector bStar, Rcpp::NumericMatrix A, Rcpp::NumericVector y, Rcpp::NumericMatrix x, Rcpp::NumericMatrix mu, Rcpp::NumericMatrix P, Rcpp::NumericVector alpha, Rcpp::NumericVector wt, std::string family, std::string link, int Gridtype, int n, int n_envopt, bool sortgrid, bool use_opencl, bool verbose);
RcppExport SEXP _glmbayes_EnvelopeBuild_cpp_export(SEXP bStarSEXP, SEXP ASEXP, SEXP ySEXP, SEXP xSEXP, SEXP muSEXP, SEXP PSEXP, SEXP alphaSEXP, SEXP wtSEXP, SEXP familySEXP, SEXP linkSEXP, SEXP GridtypeSEXP, SEXP nSEXP, SEXP n_envoptSEXP, SEXP sortgridSEXP, SEXP use_openclSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type bStar(bStarSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type A(ASEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type mu(muSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type P(PSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type wt(wtSEXP);
    Rcpp::traits::input_parameter< std::string >::type family(familySEXP);
    Rcpp::traits::input_parameter< std::string >::type link(linkSEXP);
    Rcpp::traits::input_parameter< int >::type Gridtype(GridtypeSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type n_envopt(n_envoptSEXP);
    Rcpp::traits::input_parameter< bool >::type sortgrid(sortgridSEXP);
    Rcpp::traits::input_parameter< bool >::type use_opencl(use_openclSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(EnvelopeBuild_cpp_export(bStar, A, y, x, mu, P, alpha, wt, family, link, Gridtype, n, n_envopt, sortgrid, use_opencl, verbose));
    return rcpp_result_gen;
END_RCPP
}
// EnvelopeBuild_Ind_Normal_Gamma_cpp_export
Rcpp::List EnvelopeBuild_Ind_Normal_Gamma_cpp_export(const Rcpp::NumericVector& bStar, const Rcpp::NumericMatrix& A, const Rcpp::NumericVector& y, const Rcpp::NumericMatrix& x, const Rcpp::NumericMatrix& mu, const Rcpp::NumericMatrix& P, const Rcpp::NumericVector& alpha, const Rcpp::NumericVector& wt, const std::string& family, const std::string& link, int Gridtype, int n, int n_envopt, bool sortgrid, bool use_opencl, bool verbose);
RcppExport SEXP _glmbayes_EnvelopeBuild_Ind_Normal_Gamma_cpp_export(SEXP bStarSEXP, SEXP ASEXP, SEXP ySEXP, SEXP xSEXP, SEXP muSEXP, SEXP PSEXP, SEXP alphaSEXP, SEXP wtSEXP, SEXP familySEXP, SEXP linkSEXP, SEXP GridtypeSEXP, SEXP nSEXP, SEXP n_envoptSEXP, SEXP sortgridSEXP, SEXP use_openclSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type bStar(bStarSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type P(PSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type wt(wtSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type family(familySEXP);
    Rcpp::traits::input_parameter< const std::string& >::type link(linkSEXP);
    Rcpp::traits::input_parameter< int >::type Gridtype(GridtypeSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type n_envopt(n_envoptSEXP);
    Rcpp::traits::input_parameter< bool >::type sortgrid(sortgridSEXP);
    Rcpp::traits::input_parameter< bool >::type use_opencl(use_openclSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(EnvelopeBuild_Ind_Normal_Gamma_cpp_export(bStar, A, y, x, mu, P, alpha, wt, family, link, Gridtype, n, n_envopt, sortgrid, use_opencl, verbose));
    return rcpp_result_gen;
END_RCPP
}
// EnvelopeEval_cpp_export
Rcpp::List EnvelopeEval_cpp_export(const Rcpp::NumericMatrix& G4, const Rcpp::NumericVector& y, const Rcpp::NumericMatrix& x, const Rcpp::NumericMatrix& mu, const Rcpp::NumericMatrix& P, const Rcpp::NumericVector& alpha, const Rcpp::NumericVector& wt, const std::string& family, const std::string& link, bool use_opencl, bool verbose);
RcppExport SEXP _glmbayes_EnvelopeEval_cpp_export(SEXP G4SEXP, SEXP ySEXP, SEXP xSEXP, SEXP muSEXP, SEXP PSEXP, SEXP alphaSEXP, SEXP wtSEXP, SEXP familySEXP, SEXP linkSEXP, SEXP use_openclSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type G4(G4SEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type P(PSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type wt(wtSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type family(familySEXP);
    Rcpp::traits::input_parameter< const std::string& >::type link(linkSEXP);
    Rcpp::traits::input_parameter< bool >::type use_opencl(use_openclSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(EnvelopeEval_cpp_export(G4, y, x, mu, P, alpha, wt, family, link, use_opencl, verbose));
    return rcpp_result_gen;
END_RCPP
}
// EnvelopeDispersionBuild_cpp_export
Rcpp::List EnvelopeDispersionBuild_cpp_export(const Rcpp::List& Env, double Shape, double Rate, const Rcpp::NumericMatrix& P, const Rcpp::NumericVector& y, const Rcpp::NumericMatrix& x, const Rcpp::NumericVector& alpha, int n_obs, double RSS_post, double RSS_ML, const Rcpp::NumericMatrix& mu, const Rcpp::NumericVector& wt, double max_disp_perc, Rcpp::Nullable<double> disp_lower, Rcpp::Nullable<double> disp_upper, bool verbose, bool use_parallel);
RcppExport SEXP _glmbayes_EnvelopeDispersionBuild_cpp_export(SEXP EnvSEXP, SEXP ShapeSEXP, SEXP RateSEXP, SEXP PSEXP, SEXP ySEXP, SEXP xSEXP, SEXP alphaSEXP, SEXP n_obsSEXP, SEXP RSS_postSEXP, SEXP RSS_MLSEXP, SEXP muSEXP, SEXP wtSEXP, SEXP max_disp_percSEXP, SEXP disp_lowerSEXP, SEXP disp_upperSEXP, SEXP verboseSEXP, SEXP use_parallelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type Env(EnvSEXP);
    Rcpp::traits::input_parameter< double >::type Shape(ShapeSEXP);
    Rcpp::traits::input_parameter< double >::type Rate(RateSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type P(PSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< int >::type n_obs(n_obsSEXP);
    Rcpp::traits::input_parameter< double >::type RSS_post(RSS_postSEXP);
    Rcpp::traits::input_parameter< double >::type RSS_ML(RSS_MLSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type wt(wtSEXP);
    Rcpp::traits::input_parameter< double >::type max_disp_perc(max_disp_percSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type disp_lower(disp_lowerSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type disp_upper(disp_upperSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< bool >::type use_parallel(use_parallelSEXP);
    rcpp_result_gen = Rcpp::wrap(EnvelopeDispersionBuild_cpp_export(Env, Shape, Rate, P, y, x, alpha, n_obs, RSS_post, RSS_ML, mu, wt, max_disp_perc, disp_lower, disp_upper, verbose, use_parallel));
    return rcpp_result_gen;
END_RCPP
}
// EnvelopeOrchestrator_cpp_export
Rcpp::List EnvelopeOrchestrator_cpp_export(const Rcpp::NumericVector& bstar2, const Rcpp::NumericMatrix& A, const Rcpp::NumericVector& y, const Rcpp::NumericMatrix& x2, const Rcpp::NumericMatrix& mu2, const Rcpp::NumericMatrix& P2, const Rcpp::NumericVector& alpha, const Rcpp::NumericVector& wt, int n, int Gridtype, Rcpp::Nullable<int> n_envopt, double shape, double rate, double RSS_Post2, double RSS_ML, double max_disp_perc, Rcpp::Nullable<double> disp_lower, Rcpp::Nullable<double> disp_upper, bool use_parallel, bool use_opencl, bool verbose);
RcppExport SEXP _glmbayes_EnvelopeOrchestrator_cpp_export(SEXP bstar2SEXP, SEXP ASEXP, SEXP ySEXP, SEXP x2SEXP, SEXP mu2SEXP, SEXP P2SEXP, SEXP alphaSEXP, SEXP wtSEXP, SEXP nSEXP, SEXP GridtypeSEXP, SEXP n_envoptSEXP, SEXP shapeSEXP, SEXP rateSEXP, SEXP RSS_Post2SEXP, SEXP RSS_MLSEXP, SEXP max_disp_percSEXP, SEXP disp_lowerSEXP, SEXP disp_upperSEXP, SEXP use_parallelSEXP, SEXP use_openclSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type bstar2(bstar2SEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type x2(x2SEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type mu2(mu2SEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type P2(P2SEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type wt(wtSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type Gridtype(GridtypeSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<int> >::type n_envopt(n_envoptSEXP);
    Rcpp::traits::input_parameter< double >::type shape(shapeSEXP);
    Rcpp::traits::input_parameter< double >::type rate(rateSEXP);
    Rcpp::traits::input_parameter< double >::type RSS_Post2(RSS_Post2SEXP);
    Rcpp::traits::input_parameter< double >::type RSS_ML(RSS_MLSEXP);
    Rcpp::traits::input_parameter< double >::type max_disp_perc(max_disp_percSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type disp_lower(disp_lowerSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type disp_upper(disp_upperSEXP);
    Rcpp::traits::input_parameter< bool >::type use_parallel(use_parallelSEXP);
    Rcpp::traits::input_parameter< bool >::type use_opencl(use_openclSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(EnvelopeOrchestrator_cpp_export(bstar2, A, y, x2, mu2, P2, alpha, wt, n, Gridtype, n_envopt, shape, rate, RSS_Post2, RSS_ML, max_disp_perc, disp_lower, disp_upper, use_parallel, use_opencl, verbose));
    return rcpp_result_gen;
END_RCPP
}
// EnvelopeCentering_cpp_export
Rcpp::List EnvelopeCentering_cpp_export(const Rcpp::NumericVector& y, const Rcpp::NumericMatrix& x, const Rcpp::NumericVector& mu, const Rcpp::NumericMatrix& P, const Rcpp::NumericVector& offset, const Rcpp::NumericVector& wt, double shape, double rate, int Gridtype, bool verbose);
RcppExport SEXP _glmbayes_EnvelopeCentering_cpp_export(SEXP ySEXP, SEXP xSEXP, SEXP muSEXP, SEXP PSEXP, SEXP offsetSEXP, SEXP wtSEXP, SEXP shapeSEXP, SEXP rateSEXP, SEXP GridtypeSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type P(PSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type wt(wtSEXP);
    Rcpp::traits::input_parameter< double >::type shape(shapeSEXP);
    Rcpp::traits::input_parameter< double >::type rate(rateSEXP);
    Rcpp::traits::input_parameter< int >::type Gridtype(GridtypeSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(EnvelopeCentering_cpp_export(y, x, mu, P, offset, wt, shape, rate, Gridtype, verbose));
    return rcpp_result_gen;
END_RCPP
}
// EnvelopeSet_Grid_cpp_export
Rcpp::List EnvelopeSet_Grid_cpp_export(const Rcpp::NumericMatrix& GIndex, const Rcpp::NumericMatrix& cbars, const Rcpp::NumericMatrix& Lint);
RcppExport SEXP _glmbayes_EnvelopeSet_Grid_cpp_export(SEXP GIndexSEXP, SEXP cbarsSEXP, SEXP LintSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type GIndex(GIndexSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type cbars(cbarsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type Lint(LintSEXP);
    rcpp_result_gen = Rcpp::wrap(EnvelopeSet_Grid_cpp_export(GIndex, cbars, Lint));
    return rcpp_result_gen;
END_RCPP
}
// EnvelopeSet_LogP_cpp_export
Rcpp::List EnvelopeSet_LogP_cpp_export(const Rcpp::NumericMatrix& logP, const Rcpp::NumericVector& NegLL, const Rcpp::NumericMatrix& cbars, const Rcpp::NumericMatrix& G3);
RcppExport SEXP _glmbayes_EnvelopeSet_LogP_cpp_export(SEXP logPSEXP, SEXP NegLLSEXP, SEXP cbarsSEXP, SEXP G3SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type logP(logPSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type NegLL(NegLLSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type cbars(cbarsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type G3(G3SEXP);
    rcpp_result_gen = Rcpp::wrap(EnvelopeSet_LogP_cpp_export(logP, NegLL, cbars, G3));
    return rcpp_result_gen;
END_RCPP
}
// rIndepNormalGammaReg_std_cpp_export
Rcpp::List rIndepNormalGammaReg_std_cpp_export(int n, const Rcpp::NumericVector& y, const Rcpp::NumericMatrix& x, const Rcpp::NumericMatrix& mu, const Rcpp::NumericMatrix& P, const Rcpp::NumericVector& alpha, const Rcpp::NumericVector& wt, const Rcpp::Function& f2, const Rcpp::List& Envelope, const Rcpp::List& gamma_list, const Rcpp::List& UB_list, const Rcpp::CharacterVector& family, const Rcpp::CharacterVector& link, bool progbar, bool verbose);
RcppExport SEXP _glmbayes_rIndepNormalGammaReg_std_cpp_export(SEXP nSEXP, SEXP ySEXP, SEXP xSEXP, SEXP muSEXP, SEXP PSEXP, SEXP alphaSEXP, SEXP wtSEXP, SEXP f2SEXP, SEXP EnvelopeSEXP, SEXP gamma_listSEXP, SEXP UB_listSEXP, SEXP familySEXP, SEXP linkSEXP, SEXP progbarSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type P(PSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type wt(wtSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Function& >::type f2(f2SEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type Envelope(EnvelopeSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type gamma_list(gamma_listSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type UB_list(UB_listSEXP);
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector& >::type family(familySEXP);
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector& >::type link(linkSEXP);
    Rcpp::traits::input_parameter< bool >::type progbar(progbarSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(rIndepNormalGammaReg_std_cpp_export(n, y, x, mu, P, alpha, wt, f2, Envelope, gamma_list, UB_list, family, link, progbar, verbose));
    return rcpp_result_gen;
END_RCPP
}
// rIndepNormalGammaReg_std_parallel_cpp_export
Rcpp::List rIndepNormalGammaReg_std_parallel_cpp_export(int n, const Rcpp::NumericVector& y, const Rcpp::NumericMatrix& x, const Rcpp::NumericMatrix& mu, const Rcpp::NumericMatrix& P, const Rcpp::NumericVector& alpha, const Rcpp::NumericVector& wt, const Rcpp::Function& f2, const Rcpp::List& Envelope, const Rcpp::List& gamma_list, const Rcpp::List& UB_list, const Rcpp::CharacterVector& family, const Rcpp::CharacterVector& link, bool progbar, bool verbose);
RcppExport SEXP _glmbayes_rIndepNormalGammaReg_std_parallel_cpp_export(SEXP nSEXP, SEXP ySEXP, SEXP xSEXP, SEXP muSEXP, SEXP PSEXP, SEXP alphaSEXP, SEXP wtSEXP, SEXP f2SEXP, SEXP EnvelopeSEXP, SEXP gamma_listSEXP, SEXP UB_listSEXP, SEXP familySEXP, SEXP linkSEXP, SEXP progbarSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type P(PSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type wt(wtSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Function& >::type f2(f2SEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type Envelope(EnvelopeSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type gamma_list(gamma_listSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type UB_list(UB_listSEXP);
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector& >::type family(familySEXP);
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector& >::type link(linkSEXP);
    Rcpp::traits::input_parameter< bool >::type progbar(progbarSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(rIndepNormalGammaReg_std_parallel_cpp_export(n, y, x, mu, P, alpha, wt, f2, Envelope, gamma_list, UB_list, family, link, progbar, verbose));
    return rcpp_result_gen;
END_RCPP
}
// glmb_Standardize_Model_cpp_export
Rcpp::List glmb_Standardize_Model_cpp_export(const Rcpp::NumericVector& y, const Rcpp::NumericMatrix& x, const Rcpp::NumericMatrix& P, const Rcpp::NumericMatrix& bstar, const Rcpp::NumericMatrix& A1);
RcppExport SEXP _glmbayes_glmb_Standardize_Model_cpp_export(SEXP ySEXP, SEXP xSEXP, SEXP PSEXP, SEXP bstarSEXP, SEXP A1SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type P(PSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type bstar(bstarSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type A1(A1SEXP);
    rcpp_result_gen = Rcpp::wrap(glmb_Standardize_Model_cpp_export(y, x, P, bstar, A1));
    return rcpp_result_gen;
END_RCPP
}
// has_opencl_cpp_export
bool has_opencl_cpp_export();
RcppExport SEXP _glmbayes_has_opencl_cpp_export() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(has_opencl_cpp_export());
    return rcpp_result_gen;
END_RCPP
}
// get_opencl_core_count_cpp_export
int get_opencl_core_count_cpp_export();
RcppExport SEXP _glmbayes_get_opencl_core_count_cpp_export() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(get_opencl_core_count_cpp_export());
    return rcpp_result_gen;
END_RCPP
}
// gpu_names_cpp_export
Rcpp::CharacterVector gpu_names_cpp_export();
RcppExport SEXP _glmbayes_gpu_names_cpp_export() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(gpu_names_cpp_export());
    return rcpp_result_gen;
END_RCPP
}
// debug_likelihood_program_cpp_export
Rcpp::List debug_likelihood_program_cpp_export(std::string family, std::string link);
RcppExport SEXP _glmbayes_debug_likelihood_program_cpp_export(SEXP familySEXP, SEXP linkSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type family(familySEXP);
    Rcpp::traits::input_parameter< std::string >::type link(linkSEXP);
    rcpp_result_gen = Rcpp::wrap(debug_likelihood_program_cpp_export(family, link));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_glmbayes_rNormalGLM_cpp_export", (DL_FUNC) &_glmbayes_rNormalGLM_cpp_export, 18},
    {"_glmbayes_rNormalGLMBlocks_cpp_export", (DL_FUNC) &_glmbayes_rNormalGLMBlocks_cpp_export, 19},
    {"_glmbayes_rNormalReg_cpp_export", (DL_FUNC) &_glmbayes_rNormalReg_cpp_export, 14},
    {"_glmbayes_rIndepNormalGammaReg_cpp_export", (DL_FUNC) &_glmbayes_rIndepNormalGammaReg_cpp_export, 18},
    {"_glmbayes_rNormalGammaReg_cpp_export", (DL_FUNC) &_glmbayes_rNormalGammaReg_cpp_export, 13},
    {"_glmbayes_rGammaGaussian_cpp_export", (DL_FUNC) &_glmbayes_rGammaGaussian_cpp_export, 11},
    {"_glmbayes_rGammaGamma_cpp_export", (DL_FUNC) &_glmbayes_rGammaGamma_cpp_export, 12},
    {"_glmbayes_rNormalGLM_std_cpp_export", (DL_FUNC) &_glmbayes_rNormalGLM_std_cpp_export, 13},
    {"_glmbayes_EnvelopeSize_cpp_export", (DL_FUNC) &_glmbayes_EnvelopeSize_cpp_export, 7},
    {"_glmbayes_EnvelopeBuild_cpp_export", (DL_FUNC) &_glmbayes_EnvelopeBuild_cpp_export, 16},
    {"_glmbayes_EnvelopeBuild_Ind_Normal_Gamma_cpp_export", (DL_FUNC) &_glmbayes_EnvelopeBuild_Ind_Normal_Gamma_cpp_export, 16},
    {"_glmbayes_EnvelopeEval_cpp_export", (DL_FUNC) &_glmbayes_EnvelopeEval_cpp_export, 11},
    {"_glmbayes_EnvelopeDispersionBuild_cpp_export", (DL_FUNC) &_glmbayes_EnvelopeDispersionBuild_cpp_export, 17},
    {"_glmbayes_EnvelopeOrchestrator_cpp_export", (DL_FUNC) &_glmbayes_EnvelopeOrchestrator_cpp_export, 21},
    {"_glmbayes_EnvelopeCentering_cpp_export", (DL_FUNC) &_glmbayes_EnvelopeCentering_cpp_export, 10},
    {"_glmbayes_EnvelopeSet_Grid_cpp_export", (DL_FUNC) &_glmbayes_EnvelopeSet_Grid_cpp_export, 3},
    {"_glmbayes_EnvelopeSet_LogP_cpp_export", (DL_FUNC) &_glmbayes_EnvelopeSet_LogP_cpp_export, 4},
    {"_glmbayes_rIndepNormalGammaReg_std_cpp_export", (DL_FUNC) &_glmbayes_rIndepNormalGammaReg_std_cpp_export, 15},
    {"_glmbayes_rIndepNormalGammaReg_std_parallel_cpp_export", (DL_FUNC) &_glmbayes_rIndepNormalGammaReg_std_parallel_cpp_export, 15},
    {"_glmbayes_glmb_Standardize_Model_cpp_export", (DL_FUNC) &_glmbayes_glmb_Standardize_Model_cpp_export, 5},
    {"_glmbayes_has_opencl_cpp_export", (DL_FUNC) &_glmbayes_has_opencl_cpp_export, 0},
    {"_glmbayes_get_opencl_core_count_cpp_export", (DL_FUNC) &_glmbayes_get_opencl_core_count_cpp_export, 0},
    {"_glmbayes_gpu_names_cpp_export", (DL_FUNC) &_glmbayes_gpu_names_cpp_export, 0},
    {"_glmbayes_debug_likelihood_program_cpp_export", (DL_FUNC) &_glmbayes_debug_likelihood_program_cpp_export, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_glmbayes(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
