# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.EnvelopeBuild_cpp <- function(bStar, A, y, x, mu, P, alpha, wt, family = "binomial", link = "logit", Gridtype = 2L, n = 1L, sortgrid = FALSE) {
    .Call('_glmbayes_EnvelopeBuild_c', PACKAGE = 'glmbayes', bStar, A, y, x, mu, P, alpha, wt, family, link, Gridtype, n, sortgrid)
}

.EnvelopeBuild_Ind_Normal_Gamma <- function(bStar, A, y, x, mu, P, alpha, wt, family = "binomial", link = "logit", Gridtype = 2L, n = 1L, sortgrid = FALSE) {
    .Call('_glmbayes_EnvelopeBuild_Ind_Normal_Gamma', PACKAGE = 'glmbayes', bStar, A, y, x, mu, P, alpha, wt, family, link, Gridtype, n, sortgrid)
}

.Set_Grid_cpp <- function(GIndex, cbars, Lint) {
    .Call('_glmbayes_Set_Grid', PACKAGE = 'glmbayes', GIndex, cbars, Lint)
}

.setlogP_cpp <- function(logP, NegLL, cbars, G3) {
    .Call('_glmbayes_setlogP', PACKAGE = 'glmbayes', logP, NegLL, cbars, G3)
}

.RSS <- function(y, x, b, alpha, wt) {
    .Call('_glmbayes_RSS', PACKAGE = 'glmbayes', y, x, b, alpha, wt)
}

.f2_gaussian_vector <- function(b, y, x, mu, P, alpha, wt) {
    .Call('_glmbayes_f2_gaussian', PACKAGE = 'glmbayes', b, y, x, mu, P, alpha, wt)
}

.Inv_f3_gaussian <- function(cbars, y, x, mu, P, alpha, wt) {
    .Call('_glmbayes_Inv_f3_gaussian', PACKAGE = 'glmbayes', cbars, y, x, mu, P, alpha, wt)
}

.rindep_norm_gamma_reg_std_cpp <- function(n, y, x, mu, P, alpha, wt, f2, Envelope, family, link, progbar = 1L) {
    .Call('_glmbayes_rindep_norm_gamma_reg_std_cpp', PACKAGE = 'glmbayes', n, y, x, mu, P, alpha, wt, f2, Envelope, family, link, progbar)
}

.rindep_norm_gamma_reg_std_V2_cpp <- function(n, y, x, mu, P, alpha, wt, f2, Envelope, gamma_list, UB_list, family, link, progbar = 1L) {
    .Call('_glmbayes_rindep_norm_gamma_reg_std_v2_cpp', PACKAGE = 'glmbayes', n, y, x, mu, P, alpha, wt, f2, Envelope, gamma_list, UB_list, family, link, progbar)
}

.rindep_norm_gamma_reg_std_V3_cpp <- function(n, y, x, mu, P, alpha, wt, f2, Envelope, gamma_list, UB_list, family, link, progbar = 1L) {
    .Call('_glmbayes_rindep_norm_gamma_reg_std_v3_cpp', PACKAGE = 'glmbayes', n, y, x, mu, P, alpha, wt, f2, Envelope, gamma_list, UB_list, family, link, progbar)
}

.rindep_norm_gamma_reg_std_V4_cpp <- function(n, y, x, mu, P, alpha, wt, f2, Envelope, gamma_list, UB_list, family, link, progbar = 1L) {
    .Call('_glmbayes_rindep_norm_gamma_reg_std_v4_cpp', PACKAGE = 'glmbayes', n, y, x, mu, P, alpha, wt, f2, Envelope, gamma_list, UB_list, family, link, progbar)
}

.rindep_norm_gamma_reg_std_V5_cpp <- function(n, y, x, mu, P, alpha, wt, f2, Envelope, gamma_list, UB_list, family, link, progbar = 1L) {
    .Call('_glmbayes_rindep_norm_gamma_reg_std_v5_cpp', PACKAGE = 'glmbayes', n, y, x, mu, P, alpha, wt, f2, Envelope, gamma_list, UB_list, family, link, progbar)
}

.glmb_Standardize_Model_cpp <- function(y, x, P, bstar, A1) {
    .Call('_glmbayes_glmb_Standardize_Model', PACKAGE = 'glmbayes', y, x, P, bstar, A1)
}

.rnnorm_reg_std_cpp <- function(n, y, x, mu, P, alpha, wt, f2, Envelope, family, link, progbar = 1L) {
    .Call('_glmbayes_rnnorm_reg_std_cpp', PACKAGE = 'glmbayes', n, y, x, mu, P, alpha, wt, f2, Envelope, family, link, progbar)
}

.rnnorm_reg_cpp <- function(n, y, x, mu, P, offset, wt, dispersion, f2, f3, start, family = "binomial", link = "logit", Gridtype = 2L) {
    .Call('_glmbayes_rnnorm_reg_cpp', PACKAGE = 'glmbayes', n, y, x, mu, P, offset, wt, dispersion, f2, f3, start, family, link, Gridtype)
}

.rnorm_reg_cpp <- function(n, y, x, mu, P, offset, wt, dispersion, f2, f3, start, family = "gaussian", link = "identity", Gridtype = 2L) {
    .Call('_glmbayes_rnorm_reg_cpp', PACKAGE = 'glmbayes', n, y, x, mu, P, offset, wt, dispersion, f2, f3, start, family, link, Gridtype)
}

