# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Set_Grid <- function(GIndex, cbars, Lint) {
    .Call('glmbayes_Set_Grid', PACKAGE = 'glmbayes', GIndex, cbars, Lint)
}

setlogP <- function(logP, NegLL, cbars, G3) {
    .Call('glmbayes_setlogP', PACKAGE = 'glmbayes', logP, NegLL, cbars, G3)
}

f1_binomial_logit <- function(b, y, x, alpha, wt) {
    .Call('glmbayes_f1_binomial_logit', PACKAGE = 'glmbayes', b, y, x, alpha, wt)
}

f2_binomial_logit <- function(b, y, x, mu, P, alpha, wt, progbar = 0L) {
    .Call('glmbayes_f2_binomial_logit', PACKAGE = 'glmbayes', b, y, x, mu, P, alpha, wt, progbar)
}

f3_binomial_logit <- function(b, y, x, mu, P, alpha, wt, progbar = 0L) {
    .Call('glmbayes_f3_binomial_logit', PACKAGE = 'glmbayes', b, y, x, mu, P, alpha, wt, progbar)
}

f4_binomial_logit <- function(b, y, x, mu, P, alpha, wt, NegLL, progbar = 0L) {
    .Call('glmbayes_f4_binomial_logit', PACKAGE = 'glmbayes', b, y, x, mu, P, alpha, wt, NegLL, progbar)
}

f1_binomial_probit <- function(b, y, x, alpha, wt) {
    .Call('glmbayes_f1_binomial_probit', PACKAGE = 'glmbayes', b, y, x, alpha, wt)
}

f2_binomial_probit <- function(b, y, x, mu, P, alpha, wt, progbar = 0L) {
    .Call('glmbayes_f2_binomial_probit', PACKAGE = 'glmbayes', b, y, x, mu, P, alpha, wt, progbar)
}

f3_binomial_probit <- function(b, y, x, mu, P, alpha, wt, progbar = 0L) {
    .Call('glmbayes_f3_binomial_probit', PACKAGE = 'glmbayes', b, y, x, mu, P, alpha, wt, progbar)
}

f4_binomial_probit <- function(b, y, x, mu, P, alpha, wt, NegLL, progbar = 0L) {
    .Call('glmbayes_f4_binomial_probit', PACKAGE = 'glmbayes', b, y, x, mu, P, alpha, wt, NegLL, progbar)
}

f1_binomial_cloglog <- function(b, y, x, alpha, wt) {
    .Call('glmbayes_f1_binomial_cloglog', PACKAGE = 'glmbayes', b, y, x, alpha, wt)
}

f2_binomial_cloglog <- function(b, y, x, mu, P, alpha, wt, progbar = 0L) {
    .Call('glmbayes_f2_binomial_cloglog', PACKAGE = 'glmbayes', b, y, x, mu, P, alpha, wt, progbar)
}

f3_binomial_cloglog <- function(b, y, x, mu, P, alpha, wt, progbar = 0L) {
    .Call('glmbayes_f3_binomial_cloglog', PACKAGE = 'glmbayes', b, y, x, mu, P, alpha, wt, progbar)
}

f4_binomial_cloglog <- function(b, y, x, mu, P, alpha, wt, NegLL, progbar = 0L) {
    .Call('glmbayes_f4_binomial_cloglog', PACKAGE = 'glmbayes', b, y, x, mu, P, alpha, wt, NegLL, progbar)
}

f1_gamma <- function(b, y, x, alpha, wt) {
    .Call('glmbayes_f1_gamma', PACKAGE = 'glmbayes', b, y, x, alpha, wt)
}

f2_gamma <- function(b, y, x, mu, P, alpha, wt, progbar = 0L) {
    .Call('glmbayes_f2_gamma', PACKAGE = 'glmbayes', b, y, x, mu, P, alpha, wt, progbar)
}

f3_gamma <- function(b, y, x, mu, P, alpha, wt, progbar = 0L) {
    .Call('glmbayes_f3_gamma', PACKAGE = 'glmbayes', b, y, x, mu, P, alpha, wt, progbar)
}

f4_gamma <- function(b, y, x, mu, P, alpha, wt, NegLL, progbar = 0L) {
    .Call('glmbayes_f4_gamma', PACKAGE = 'glmbayes', b, y, x, mu, P, alpha, wt, NegLL, progbar)
}

f1_gaussian <- function(b, y, x, alpha, wt) {
    .Call('glmbayes_f1_gaussian', PACKAGE = 'glmbayes', b, y, x, alpha, wt)
}

f2_gaussian <- function(b, y, x, mu, P, alpha, wt) {
    .Call('glmbayes_f2_gaussian', PACKAGE = 'glmbayes', b, y, x, mu, P, alpha, wt)
}

f3_gaussian <- function(b, y, x, mu, P, alpha, wt) {
    .Call('glmbayes_f3_gaussian', PACKAGE = 'glmbayes', b, y, x, mu, P, alpha, wt)
}

f1_poisson <- function(b, y, x, alpha, wt) {
    .Call('glmbayes_f1_poisson', PACKAGE = 'glmbayes', b, y, x, alpha, wt)
}

f2_poisson <- function(b, y, x, mu, P, alpha, wt, progbar = 0L) {
    .Call('glmbayes_f2_poisson', PACKAGE = 'glmbayes', b, y, x, mu, P, alpha, wt, progbar)
}

f3_poisson <- function(b, y, x, mu, P, alpha, wt, progbar = 0L) {
    .Call('glmbayes_f3_poisson', PACKAGE = 'glmbayes', b, y, x, mu, P, alpha, wt, progbar)
}

f4_poisson <- function(b, y, x, mu, P, alpha, wt, NegLL, progbar = 0L) {
    .Call('glmbayes_f4_poisson', PACKAGE = 'glmbayes', b, y, x, mu, P, alpha, wt, NegLL, progbar)
}

progress_bar2 <- function(x, N) {
    invisible(.Call('glmbayes_progress_bar2', PACKAGE = 'glmbayes', x, N))
}

glmbsim_cpp <- function(n, y, x, mu, P, alpha, wt, f2, Envelope, family, link, progbar = 1L) {
    .Call('glmbayes_glmbsim_cpp', PACKAGE = 'glmbayes', n, y, x, mu, P, alpha, wt, f2, Envelope, family, link, progbar)
}

glmbenvelope_c <- function(bStar, A, y, x, mu, P, alpha, wt, family = "binomial", link = "logit", Gridtype = 2L, n = 1L, sortgrid = FALSE) {
    .Call('glmbayes_glmbenvelope_c', PACKAGE = 'glmbayes', bStar, A, y, x, mu, P, alpha, wt, family, link, Gridtype, n, sortgrid)
}

optPostMode <- function(y, x, mu, P, alpha, wt, b, bstar, family = "binomial", link = "logit") {
    .Call('glmbayes_optPostMode', PACKAGE = 'glmbayes', y, x, mu, P, alpha, wt, b, bstar, family, link)
}

glmbsim_NGauss_cpp <- function(n, y, x, mu, P, offset2, wt, dispersion, famfunc, f1, f2, f3, start, family = "binomial", link = "logit", Gridtype = 2L) {
    .Call('glmbayes_glmbsim_NGauss_cpp', PACKAGE = 'glmbayes', n, y, x, mu, P, offset2, wt, dispersion, famfunc, f1, f2, f3, start, family, link, Gridtype)
}

glmbsim_Gauss_cpp <- function(n, y, x, mu, P, offset2, wt, dispersion, famfunc, f1, f2, f3, start, family = "binomial", link = "logit", Gridtype = 2L) {
    .Call('glmbayes_glmbsim_Gauss_cpp', PACKAGE = 'glmbayes', n, y, x, mu, P, offset2, wt, dispersion, famfunc, f1, f2, f3, start, family, link, Gridtype)
}

glmbsim_NGauss2_cpp <- function(n, y, x, mu, P, offset2, wt, dispersion, famfunc, f1, f2, f3, start, family = "binomial", link = "logit", Gridtype = 2L) {
    .Call('glmbayes_glmbsim_NGauss2_cpp', PACKAGE = 'glmbayes', n, y, x, mu, P, offset2, wt, dispersion, famfunc, f1, f2, f3, start, family, link, Gridtype)
}

rglmb_rand_cpp <- function(n, y, x, mu, P_0, P, offset2, wt, dispersion, famfunc, f1, f2, f3, start, PD, family = "binomial", link = "logit", Gridtype = 2L, epsilon_converge = 0.01) {
    .Call('glmbayes_rglmb_rand_cpp', PACKAGE = 'glmbayes', n, y, x, mu, P_0, P, offset2, wt, dispersion, famfunc, f1, f2, f3, start, PD, family, link, Gridtype, epsilon_converge)
}

