# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.EnvelopeBuild_cpp <- function(bStar, A, y, x, mu, P, alpha, wt, family, link, Gridtype, n, sortgrid, use_opencl, verbose) {
    .Call(`_glmbayes_EnvelopeBuild_c`, bStar, A, y, x, mu, P, alpha, wt, family, link, Gridtype, n, sortgrid, use_opencl, verbose)
}

.EnvelopeBuild_Ind_Normal_Gamma <- function(bStar, A, y, x, mu, P, alpha, wt, family = "binomial", link = "logit", Gridtype = 2L, n = 1L, sortgrid = FALSE) {
    .Call(`_glmbayes_EnvelopeBuild_Ind_Normal_Gamma`, bStar, A, y, x, mu, P, alpha, wt, family, link, Gridtype, n, sortgrid)
}

.Set_Grid_cpp <- function(GIndex, cbars, Lint) {
    .Call(`_glmbayes_Set_Grid`, GIndex, cbars, Lint)
}

.setlogP_cpp <- function(logP, NegLL, cbars, G3) {
    .Call(`_glmbayes_setlogP`, logP, NegLL, cbars, G3)
}

arithmetic_test_wrapper <- function() {
    .Call(`_glmbayes_arithmetic_test_wrapper`)
}

f2_binomial_logit_prep <- function(b, y, x, mu, P, alpha, wt, progbar) {
    .Call(`_glmbayes_f2_binomial_logit_prep`, b, y, x, mu, P, alpha, wt, progbar)
}

f2_binomial_logit_prep_v3 <- function(b, y, x, mu, P, alpha, wt, progbar = 0L) {
    .Call(`_glmbayes_f2_binomial_logit_prep_v3`, b, y, x, mu, P, alpha, wt, progbar)
}

.RSS <- function(y, x, b, alpha, wt) {
    .Call(`_glmbayes_RSS`, y, x, b, alpha, wt)
}

.f2_gaussian_vector <- function(b, y, x, mu, P, alpha, wt) {
    .Call(`_glmbayes_f2_gaussian`, b, y, x, mu, P, alpha, wt)
}

.Inv_f3_gaussian <- function(cbars, y, x, mu, P, alpha, wt) {
    .Call(`_glmbayes_Inv_f3_gaussian`, cbars, y, x, mu, P, alpha, wt)
}

f2_binomial_logit_prep_opencl <- function(b, y, x, mu, P, alpha, wt, progbar) {
    .Call(`_glmbayes_f2_binomial_logit_prep_opencl`, b, y, x, mu, P, alpha, wt, progbar)
}

nmath_test_wrapper <- function() {
    .Call(`_glmbayes_nmath_test_wrapper`)
}

.rindep_norm_gamma_reg_std_cpp <- function(n, y, x, mu, P, alpha, wt, f2, Envelope, family, link, progbar = 1L) {
    .Call(`_glmbayes_rindep_norm_gamma_reg_std_cpp`, n, y, x, mu, P, alpha, wt, f2, Envelope, family, link, progbar)
}

.rindep_norm_gamma_reg_std_V2_cpp <- function(n, y, x, mu, P, alpha, wt, f2, Envelope, gamma_list, UB_list, family, link, progbar = 1L) {
    .Call(`_glmbayes_rindep_norm_gamma_reg_std_v2_cpp`, n, y, x, mu, P, alpha, wt, f2, Envelope, gamma_list, UB_list, family, link, progbar)
}

.rindep_norm_gamma_reg_std_V3_cpp <- function(n, y, x, mu, P, alpha, wt, f2, Envelope, gamma_list, UB_list, family, link, progbar = 1L) {
    .Call(`_glmbayes_rindep_norm_gamma_reg_std_v3_cpp`, n, y, x, mu, P, alpha, wt, f2, Envelope, gamma_list, UB_list, family, link, progbar)
}

.rindep_norm_gamma_reg_std_V4_cpp <- function(n, y, x, mu, P, alpha, wt, f2, Envelope, gamma_list, UB_list, family, link, progbar = 1L) {
    .Call(`_glmbayes_rindep_norm_gamma_reg_std_v4_cpp`, n, y, x, mu, P, alpha, wt, f2, Envelope, gamma_list, UB_list, family, link, progbar)
}

.rindep_norm_gamma_reg_std_V5_cpp <- function(n, y, x, mu, P, alpha, wt, f2, Envelope, gamma_list, UB_list, family, link, progbar = 1L) {
    .Call(`_glmbayes_rindep_norm_gamma_reg_std_v5_cpp`, n, y, x, mu, P, alpha, wt, f2, Envelope, gamma_list, UB_list, family, link, progbar)
}

rmath_test_wrapper <- function() {
    .Call(`_glmbayes_rmath_test_wrapper`)
}

.glmb_Standardize_Model_cpp <- function(y, x, P, bstar, A1) {
    .Call(`_glmbayes_glmb_Standardize_Model`, y, x, P, bstar, A1)
}

.rnnorm_reg_std_cpp <- function(n, y, x, mu, P, alpha, wt, f2, Envelope, family, link, progbar = 1L) {
    .Call(`_glmbayes_rnnorm_reg_std_cpp`, n, y, x, mu, P, alpha, wt, f2, Envelope, family, link, progbar)
}

test_all_args <- function(n, y, x, mu, P, alpha, wt, f2, Envelope, family, link, progbar = 1L) {
    .Call(`_glmbayes_rnnorm_reg_std_cpp_parallel`, n, y, x, mu, P, alpha, wt, f2, Envelope, family, link, progbar)
}

.rnnorm_reg_cpp <- function(n, y, x, mu, P, offset, wt, dispersion, f2, f3, start, family = "binomial", link = "logit", Gridtype = 2L, use_parallel = TRUE, use_opencl = FALSE, verbose = FALSE) {
    .Call(`_glmbayes_rnnorm_reg_cpp`, n, y, x, mu, P, offset, wt, dispersion, f2, f3, start, family, link, Gridtype, use_parallel, use_opencl, verbose)
}

.rnorm_reg_cpp <- function(n, y, x, mu, P, offset, wt, dispersion, f2, f3, start, family = "gaussian", link = "identity", Gridtype = 2L) {
    .Call(`_glmbayes_rnorm_reg_cpp`, n, y, x, mu, P, offset, wt, dispersion, f2, f3, start, family, link, Gridtype)
}

stirlerr_test_wrapper <- function() {
    .Call(`_glmbayes_stirlerr_test_wrapper`)
}

